log_level = "warn"
outputs = "All"
enable_esc_key = false

[modules]
left = ["appLauncher", "Workspaces"]
center = ["Updates", "servPing", "Clock", "CustomNotifications"]
right = ["SystemInfo", ["Tray", "Privacy", "Settings"]]

[updates]
check_cmd = "checkupdates; yay -Qua"
update_cmd = 'foot -e bash -c "yay; echo Done - Press enter to exit; read" &'

[workspaces]
enable_workspace_filling = true
max_workspaces = 9
visibility_mode = "MonitorSpecific"

[[CustomModule]]
name = "appLauncher"
icon = "Û±óº"
command = "nwg-drawer"

[[CustomModule]]
name = "servPing"
icon = "üçè"
icons.'Down' = "üçé"
icons.'Running' = "üçè"
listen_cmd = "bash -c 'while true; do if curl -s https://cloud.sudo-tiz.duckdns.org/login | grep -q Nextcloud; then echo \"{\\\"alt\\\":\\\"Running\\\"}\"; else echo \"{\\\"alt\\\":\\\"Down\\\"}\"; fi; sleep 20; done'"
command = "bash -c 'while true; do if curl -s https://cloud.sudo-tiz.duckdns.org/login | grep -q Nextcloud; then echo \"{\\\"alt\\\":\\\"Running\\\"}\"; else echo \"{\\\"alt\\\":\\\"Down\\\"}\"; fi; sleep 20; done'"

[[CustomModule]]
name = "CustomNotifications"
icon = "ÔÇ¢"
icons.'dnd.*' = "Ôá∑"
# Another regex can optionally show a red "alert" dot on the icon
alert = ".*notification"
command = "swaync-client -t -sw"
# You can optionally configure your custom module to update the UI using another command
# The output right now follows the waybar json-style output, using the `alt` and `text` field
# E.g. `{"text": "3", "alt": "notification"}`
# You can define behavior for the `text` and `alt` fields
# Any number of regex can be used to change the icon based on the alt field
listen_cmd = "swaync-client -swb"

[system_info]
indicators = [
  "DownloadSpeed",
  "UploadSpeed",
  { Disk = "/" },
  { Disk = "/mnt/backup" },
  "Cpu",
  "Memory",
  "Temperature",
]

[system_info.temperature]
sensor = "coretemp Package id 0"

[settings]
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_source_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"

lock_cmd = "hyprctl kill"
suspend_cmd = "systemctl suspend-then-hibernate"
shutdown_cmd = "shutdown now"
hibernate_cmd = "systemctl hibernate"
reboot_cmd = "systemctl reboot"
logout_cmd = "loginctl kill-user $(whoami)"

remove_airplane_btn = true
remove_idle_btn = false

indicators = [
  "Audio",
  "IdleInhibitor",
  "PowerProfile",
  "Network",
  "Vpn",
  "Bluetooth",
  "Battery",
]

[[settings.CustomButton]]
name = "Keyboard"
icon = "‚å®Ô∏è"
command = "osk_toggle"
status_command = "gsettings get org.gnome.desktop.a11y.applications screen-keyboard-enabled | grep true"

[appearance]
style = "Islands"
scale_factor = 1
primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"
workspace_colors = ["#7aa2f7", "#9ece6a"]
special_workspace_colors = ["#7aa2f7", "#9ece6a"]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"
